##############################################################
#---------------------------------------------------------####
#--generating data and noise for 4cast
#---------------------------------------------------------####
##############################################################

#######################################################
####################   GENERAL   ######################
#######################################################
[General]
verbose   = False
threshold = 1e-25
ncores    = 1
#ncores: number of cores to be used: if your CPU contains N cores available and you require
# M (>N), N is modified to M. If you set ncores<0, ncores=N.
#######################################################
[Simulations]
lmin            = 30
lmax            = 400
apply_mask      = False
apply_tf        = True
namaster_delell = 4
ell_nmt_hi   = True
ell_nmt_g    = True
ell_nmt_gxhi = True
nside    = 256
seed_hi  = 9000
seed_k   = 8000
seed_tax = 1010
#######################################################
[HI]
numin  = 980
numax  = 1260
nbands = 30
fwhm_arcmin = 40
sigma_pix = 0.022
#[sigmapix] in K units
#BINGO: (Tsys[K]: 50-70 K) sigma_pix [1yr] : 247-345 muK | sigma_pix [5yr] : 110-154 muK
#BINGO: 10/20/40 K -- 22/44/88 muK 
#######################################################
[Galaxy]
survey_name   = LSST
data_release  = Y10
type_of_field = density
path_to_file  = /data/AMARINS/LSSxHI-CODES/scripts/parameters/lsst_desc_parameters.yaml
ntomos        = 40
sigmaz        = 0.001
#######################################################
[Algorithm]
method     = ICA
wtransform = identity 
ns         = 4
#######################################################
[Outputs]
auto_hi_bins   = -1
cross_hi_bins  = -1
auto_g_bin     = 1
cross_g_bin    = 1
# be-careful with the values assume for auto/cross_g_bin
filename_hi    = cl_LOWZxLOWZ_{c}x{c}_delell{d}
filename_g     = cl_gcLSSTxgcLSST_{b}x{b}_40_0001_delell{d}
filename_gxhi  = cl_gcLSSTxLOWZ_{b}x{c}_40_0001_delell{d}
pathout        = /data/AMARINS/LSSxHI-CODES/forecast/input/hi_error_002_tffixed
#
#make sure your hdf5 file contains the same cross bins then you are requiring
dirpath_tf       = /data/AMARINS/LSSxHI-DATA/tfunction/LSST_40_0001/LSST_bin{b}_40_0001/ns4/
filename_tf_hi   = alpha_ch_sim_noiseless_smoothless.h5
filename_tf_gxhi = alpha_cx_sim_noiseless_smoothless.h5
#
save_hi        = True
save_g         = False
save_gxhi      = True
save_theory    = True
save_simulated = True
save_estimated = True
save_txt       = False
save_npz       = False
save_hdf5      = True
#######################################################
####################   PATHs   ########################
#######################################################
[PATH]
dirpath_chisel       = /data/AMARINS/chisel/scripts
dirpath_foregrounds  = /data/AMARINS/MAPS/FG256
dirpath_mask         = /data/AMARINS/MAPS/MASK
filename_foregrounds = FG_I_256_980mhz1260mhz_30bins_full_nonfrps_L0.fits
filename_mask        = mask_256_apodcutless.fits
filepath_hi   = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin{b}_40_0001_HI_cl_LOWZ.txt
filepath_g    = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin{b}_40_0001_DENSITY_cl_LOWZ.txt
filepath_gxhi = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin{b}_40_0001_HIxDENSITY_cl_LOWZ.txt

#ell_nmt: ell binning by namaster
#b: galaxy bin number (from 0 to nmax-1)
#c: hi bin number (from 0 to nmax-1)
#d: del ell (namaster binning) size
#auto_hi_bins  is a seq of numbers or <0 to assume all HI bins
#cross_hi_bins is a seq of numbers or <0 to assume all HI bins
#############################
# HI bins (from 0 to 29)
#############################
# if gbins are from 0 to 39:
#
#      bin_to_use=0 | hi_bins= 0,1,2,3
#      bin_to_use=1 | hi_bins= 4,5,6,7,8,9
#      bin_to_use=2 | hi_bins= 10,11,12,13,14
#      bin_to_use=3 | hi_bins= 15,16,17,18
#      bin_to_use=4 | hi_bins= 18,19,20,21
#      bin_to_use=5 | hi_bins= 22,23,24
#      bin_to_use=6 | hi_bins= 25,26,27
#      bin_to_use=7 | hi_bins= 28,29
#############################
# for CX
    #for i in $(seq 0 7);do python generating_data_and_noise_4forecast.py --auto_g_bin $i --cross_g_bin $i --verbose True;done
