##############################################################
#---------------------------------------------------------####
#--SIMULATIONS--------------------------------------------####
#--generating Angular Power Spectrum----------------------####
#---------------------------------------------------------####
##############################################################

#######################################################
####################   GENERAL   ######################
#######################################################
[General]
verbose = False
#project = LSSTxLOWZ_10_003
project = CMBWLxBINGO_30_980_1260
#######################################################
####################   PATHs   ########################
#######################################################
[PATH]
#sims
#filepath_field1 = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin0_10_003_HI_cl_HIGHZ.txt
#filepath_field2 = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin0_10_003_COUNT_cl_HIGHZ.txt
#filepath_cross  = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin0_10_003_HIxCOUNT_cl_HIGHZ.txt
filepath_field1 = /data/AMARINS/LSSxHI-DATA/theoretical/CMBWLxHI/CMBWL_HI_cl_nch30_980_1260.txt
filepath_field2 = /data/AMARINS/LSSxHI-DATA/theoretical/CMBWLxHI/CMBWL_CMBWL_cl_nch30_980_1260.txt
filepath_cross  = /data/AMARINS/LSSxHI-DATA/theoretical/CMBWLxHI/CMBWL_HIxCMBWL_cl_nch30_980_1260.txt
#
filepath_foregrounds = 
filepath_mask        = 

#pathout = /data/AMARINS/LSSxHI-DATA/simulations/GCxHI
pathout = /data/AMARINS/LSSxHI-DATA/simulations/CMBWLxBINGO
prefix  = 
suffix  = 
#######################################################
##################   CONTAMINANTS   ###################
#######################################################
[Contaminants]
add_foregrounds = False
apply_mask      = False

#######################################################
###################   SIMULATIONS   ###################
#######################################################
[Simulations]
nrealizations = 50
seed0         = 9000
limited_correlated_channels = False
channel_min_corr = 1
channel_max_corr = 30
amplification    = 1
channel_tax      = 1010
#amplification: to amplify the cross artificially
#channel_tax : to distinguish the alm_hi


#for i in $(seq 0 9);do python generating_APS_theory.py --bin_to_use_count $i --verbose True;done

#for i in $(seq 0 9);do mv "/data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin${i}_5_003_HI_cl_nch30_980_1260.txt" "/data/AMARINS/LSSxHI-DATA/theoretical/GCxHI/LSST_bin${i}_5_003_HI_cl_LOWZ.txt";done