    ##############################################################
#---------------------------------------------------------####
#--generating Angular Power Spectrum----------------------####
#---------------------------------------------------------####
##############################################################

#######################################################
####################   GENERAL   ######################
#######################################################
[General]
verbose   = False
threshold = 1e-25
ncores    = 1
#ncores: number of cores to be used: if your CPU contains N cores available and you require
# M (>N), N is modified to M. If you set ncores<0, ncores=N.
#######################################################
####################   COSMOLOGY   ####################
#######################################################
[Cosmology]
# Data for CAMB 
H0    = 67.4
ombh2 = 0.022
omch2 = 0.122
ns    = 0.965
As    = 0.000000002    
mnu   = 0.06
w0    = -1
wa    = 0
DE_model = fluid
#######################################################
###############   CAMB-COSMOLOGY   ####################
#######################################################
[CAMB]
zmin_integration_camb   = 0.00001
zmax_integration_camb   = 5
zsteps_integration_camb = 256
#FOr CMB, use zmaxx=1150; for galaxy, ~5
kmax    = 100
minkh   = 0.00001
maxkh   = 100
npoints = 1000000
Pk_nonlinear = True
halofit_version = takahashi
accuracyBoost   = 1.0
lsampleBoost    = 1.0
laccuracyBoost  = 1.0
##
save_Pk = False
save_Pk_at_z = 0.0, 1.0
## Not implemented yet
load_Pk = False
path_to_Pk = 
path_to_hubble_z = 
path_to_comovel_dist_z = 
#######################################################
#######################   APS   #######################
#######################################################
[APS]
#Does not change field1 as hi #to be improved later, for any field1.
#field2: [cmbwl, shear, count]   #cmbwl=CMB kappa, shear=(jth-bin) galaxy shear 
field_1 = hi
field_2 = count
l_min = 0
l_max = 767
#binning_delta_l = 1 #not implemented yet
#lmax  must be chosen such that 3*nside
#boolean variables must not be handle in terminal command
generate_cl_field_1 = 1
generate_cl_field_2 = 1
generate_cl_cross   = 1
save_all_auto_field_2 = 1
pathout = /data/AMARINS/LSSxHI-DATA/theoretical/GCxHI
#prefix  = LSST_bin{b}_5_003
prefix  = LSST_bin{b}_5_003
suffix  = HIGHZ
#For shear or count/clustering,
## EUCLID and LSST implemented
#######################################################
###################  SHEAR SURVEY   ###################
#######################################################
[SHEAR]
#survey: set which project you wanna based on 
#dataset: if you are assuming a fit modeling for a specific survey dataset
#parameters_set: to set the values for the fit modeling of redshift dist of galaxy lensing
#photometric_lkl: type of photometric likelihood used to turn the spec dist into photometric
#bin_to_use: 0,...,nch-1
#IA: intrinsic alignment
#slope_s_model 
# /data/AMARINS/CMBWLxHI-CODES/scripts/parameters/euclid_parameters.yaml
# /data/AMARINS/CMBWLxHI-CODES/scripts/parameters/lsst_desc_parameters.yaml
path_to_shear_params_file = /data/AMARINS/LSSxHI-CODES/scripts/parameters/lsst_desc_parameters.yaml
survey_shear  = LSST
dataset_shear = Y10
binning_shear = True
bin_to_use_shear      = 0
parameters_shear_set  = standard
photometric_shear_lkl = gaussian 
include_ia     = False
L_model        = eNLA
L_value        = 0
path_to_L_file = 
F_model        = eNLA
F_value        = 0
path_to_F_file = 
beta_IA        = 2.17
eta_IA         = -0.41
#Changing the yaml file
#None or -1 values will not change the standard value
nbins_shear  = 40
sigmaz_shear = -1
#zbins_edges_shear =
#######################################################
###################  CLUSTERING SURVEY   ##############
#######################################################
[COUNT]
#COUNT: CLUSTERING, number density
#RSD: redshift Spatial Distortion
#MB: Magnification Bias
#mu = <k,n>=cos(theta) in [-1,1]
#bias_model b(z): SQRT, FLAGSHIP, FLAGSHIP2022, READ, CONST
# if bias_model=CONST, bias_value is assumed
# if bias_model=READ, path_to_bias_file: path to a txt file with two colunms: z,b(z)
# L_model: (Admensional Characteristic Luminosity): eNLA, READ, CONST  #eNLA
# F_model: eNLA, NLA, CONST, READ, FIT
# /data/AMARINS/CMBWLxHI-CODES/scripts/parameters/euclid_parameters.yaml
# /data/AMARINS/CMBWLxHI-CODES/scripts/parameters/lsst_desc_parameters.yaml
path_to_count_params_file = /data/AMARINS/LSSxHI-CODES/scripts/parameters/lsst_desc_parameters.yaml
survey_count    = LSST
dataset_count   = Y1
mode_count      = photometric
bias_model      = SQRT
bias_value      = 1
path_to_bias_file = 
binning_count = True
parameters_count_set  = standard
photometric_count_lkl = gaussian 
bin_to_use_count      = 1
include_rsd   = False
include_mb    = False
mu_rsd        = 0
slope_s_model = 
slope_s_value = 0
path_to_slope_s_file = 
#---Changing the yaml file---
#None or -1 values will not change the standard value
nbins_count = 5
sigmaz_count = 0.03
#zbins_edges_count =
#######################################################
###################  HI SURVEY   ######################
#######################################################
[HI]
# It is building HI Cls with z-increasing
# [frequency] = MHz
# [binning_used] = auto, manual # If blank, it will be assumed auto
#binning_used = manual
freq_min  = 350
freq_max  = 1050
nchannels = 70
window_function_HI = tophat
###
[21cm]
#omegaHI_model: see function omegaHI_biasHI from cross_functions.py
#some models must be adapt to be used in
#jiajun - Zhang et al 2022
#padmanabhan - Padmanabhan et al 2015
#cunnington - Cunnington et al 2019 
#irfan -  Irfan et al 2021 / based on P.Bull et al 2015
#crighton
#None: omegaHI=4.86e-4/biasHI=1
omegaHI_model = 
biasHI_model  = 
# if you want to set the omegaHI and HI bias, you must 
# to set True for the parameters `fit` below AND provide 
# the values for the variables afterwards.
# Otherwise, it code will assume the model as above
fit_omegaHI = False
fit_biasHI  = False
omegaHI     = 
biasHI      = 


#for i in $(seq 0 9);do python generating_APS_theory.py --bin_to_use_count $i --verbose True;done