##############################################################
#---------------------------------------------------------####
#- CODE to calculate CROSS-leakage------------------------####
#---------------------------------------------------------####
##############################################################
# Field1: HI observed from the sky
# Field2: LSS tracer --- Here, it is implemented (gal,CMB)-convergence

##
# The data load are assumed as saved in txt format for theoretical 
# and simulated, and FITS format for the estimated one.
# The standard FITS architecture is saving the data into HDU=1
# filename of FITS data are assumed with prefix extHI, extFG and 
# mixmatrix
##

#######################################################
####################   GENERAL   ######################
#######################################################
[General]
verbose = False
#project = lowz_nch30_980_1260_nch17_23
project = highz_LSSTshearY10_bin1_nch70_350_1050
#project = lowz_LSSTshearY10_bin10_nch30_980_1260
prefix  = 
#######################################################
#######################   DATASET   ###################
#######################################################
[dataset]
nrealizations = 20
ns            = 4
nu_min_correlated = 1
nu_max_correlated = 70
#correlated with kappa (nu= 0,...,nch-1)
#######################################################
####################   PATHs   ########################
#######################################################
[PATH]
dirpath_chisel = /data/AMARINS/chisel/scripts

#theory
filepath_cross  = /data/AMARINS/CMBWLxHI-DATA/theoretical/highz_LSSTshearY10_bin1_HIxSHEAR_cl_nch70_350_1050.txt
#filepath_cross  = /data/AMARINS/CMBWLxHI-DATA/theoretical/lowz_LSSTshearY10_bin10_HIxSHEAR_cl_nch30_980_1260.txt
#filepath_cross  = /data/AMARINS/CMBWLxHI-CODES/theoretical/lowz_CMBWLxHI_cl_nch30_980_1260.txt

#simulated
dirpath_sims  = /data/AMARINS/CMBWLxHI-DATA/simulations/highz_LSSTshearY10_bin1_nch70_350_1050
#dirpath_sims  = /data/AMARINS/CMBWLxHI-DATA/simulations/lowz_LSSTshearY10_bin10_nch30_980_1260
#dirpath_sims = /data/AMARINS/CMBWLxHI-DATA/simulations/lowz_nch30_980_1260_nch17_23

#estimated
dirpath_estimated = /data/AMARINS/CMBWLxHI-DATA/FGremoval/highz_LSSTshearY10_bin1_nch70_350_1050/fullsky
#dirpath_estimated = /data/AMARINS/CMBWLxHI-DATA/FGremoval/lowz_LSSTshearY10_bin10_nch30_980_1260/fullsky
#dirpath_estimated =  /data/AMARINS/CMBWLxHI-DATA/FGremoval/lowz_nch30_980_1260_nch17_23/fullsky

#processed
dirpath_postprocessing = /data/AMARINS/CMBWLxHI-DATA/postprocessed/fullsky/highz_LSSTshearY10_bin1_nch70_350_1050
#dirpath_postprocessing = /data/AMARINS/CMBWLxHI-DATA/postprocessed/fullsky/lowz_LSSTshearY10_bin10_nch30_980_1260
#dirpath_postprocessing = /data/AMARINS/CMBWLxHI-DATA/postprocessed/fullsky/lowz_nch30_980_1260_nch17_23

#Output path
dirpath_output = /data/AMARINS/CMBWLxHI-DATA/leakage/fullsky/highz_LSSTshearY10_bin1_nch70_350_1050
#dirpath_output = /data/AMARINS/CMBWLxHI-DATA/leakage/fullsky/lowz_LSSTshearY10_bin10 _nch30_980_1260
#dirpath_output = /data/AMARINS/CMBWLxHI-DATA/leakage/fullsky/lowz_nch30_980_1260_nch25_30
